-- 콩쿠르(contest.co.kr 크롤링) 도메인을 KOPIS 오픈API 기반 클래식 연주회(concert) 도메인으로 교체.
-- "접수 마감(deadline)" 개념이 사라지고(공연은 이미 일정이 확정돼 있음), 공연장·지역·포스터가 새로 생겼다.
-- 실 데이터가 없는 시점의 전환이라 데이터 이관은 불필요, 스키마 DDL만 교체한다.

drop table if exists "concours";

create table "concert" (
    id bigint generated by default as identity,
    external_id varchar(255) not null,
    title varchar(255) not null,
    category varchar(255),
    start_date date not null,
    end_date date not null,
    venue varchar(255) not null,
    region varchar(255) not null,
    poster_url varchar(255),
    url varchar(255) not null,
    synced_at timestamp(6) not null,
    primary key (id)
);

alter table "concert" add constraint UK_concert_external_id unique (external_id);
